name: CI

# Trigger this workflow on push or pull request
on: [push, pull_request]

env:
  SRC_DIR_PATH: desktop_version

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}

    env:
      CXXFLAGS: -I/usr/local/include/SDL2
      LDFLAGS: -L/usr/local/lib

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libsdl2-dev libsdl2-mixer-dev

    - name: Install dependencies (macOS)
      if: startsWith(matrix.os, 'macos')
      run: brew install ninja sdl2 sdl2_mixer

    - name: CMake configure
      run: |
        mkdir ${SRC_DIR_PATH}/build && cd ${SRC_DIR_PATH}/build
        cmake -GNinja ..
    - name: Build
      run: ninja -C ${SRC_DIR_PATH}/build


    - name: Upload binary (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/upload-artifact@v1
      with:
        name: VVVVVV-MP-Linux-binary-$(date -Idate)
        path: desktop_version/build/VVVVVV


    - name: Build .app (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        mkdir -pv ${SRC_DIR_PATH}/build/VVVVVV-app/VVVVVV-MP.app/Contents/MacOS/
        mkdir -pv ${SRC_DIR_PATH}/build/VVVVVV-app/VVVVVV-MP.app/Contents/Resources
        mv -v ${SRC_DIR_PATH}/build/VVVVVV ${SRC_DIR_PATH}/build/VVVVVV-app/VVVVVV-MP.app/Contents/MacOS/VVVVVV
        tar -czvf VVVVVV-MP-macOS-$(date -Idate).tgz ${SRC_DIR_PATH}/build/VVVVVV-app/VVVVVV-MP.app

    - name: Upload .app (macOS)
      if: startsWith(matrix.os, 'macos')
      uses: actions/upload-artifact@v1
      with:
        name: VVVVVV-MP-macOS-$(date -Idate)
        path: VVVVVV-MP-macOS-$(date -Idate).tgz


  build-win:
    name: Build (windows-latest)

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies (Windows)
      run: |
        vcpkg install sdl2 sdl2-mixer

    - name: CMake configure
      run: |
        cd $env:SRC_DIR_PATH
        $env:LDFLAGS =  "/LIBPATH:$env:VCPKG_INSTALLATION_ROOT\installed\x86-windows\lib "
        $env:LDFLAGS += "/LIBPATH:$env:VCPKG_INSTALLATION_ROOT\installed\x86-windows\lib\manual-link"
        cmake -G "Visual Studio 16 2019" -A Win32 `
              -DSDL2_INCLUDE_DIRS="$env:VCPKG_INSTALLATION_ROOT\installed\x86-windows\include\SDL2" `
              -DSDL2_LIBRARIES="SDL2;SDL2main;SDL2_mixer" .
    - name: Build
      run: |
        cd $env:SRC_DIR_PATH
        cmake --build .

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: VVVVVV-MP-Windows-$(date -Idate)
        path: desktop_version/Debug/VVVVVV.exe
